ame: CI

on:
  push:
    branches:
      - prod
      - dev

jobs:
  login-registry:
    runs-on: self-hosted

    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

  deploy-api:
    runs-on: self-hosted
    needs: login-registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install docker
        uses: docker/setup-buildx-action@v3

      - name: API - Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/integration/api:${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev' }}

  deploy-front:
    runs-on: self-hosted
    needs: login-registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install docker
        uses: docker/setup-buildx-action@v3

      - name: Front- Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          build-args: |
            VITE_API_URL=${{ github.ref == 'refs/heads/prod' && 'https://integration.utt.fr/api' || 'https://integration.dev.uttnetgroup.fr/api' }}
            VITE_SERVICE_URL=${{ github.ref == 'refs/heads/prod' && 'https://integration.utt.fr' || 'https://integration.dev.uttnetgroup.fr' }}
          tags: |
            ${{ secrets.REGISTRY_URL }}/integration/front:${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev' }}